### ISSUE TITLE
Getting "database is locked" error when attempting to install some packages.

### ISSUE THREAD

**Issue by sergedomk** [mosquito/pypi-server#12]
```
$ pip freeze
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.1
certifi==2016.9.26
cffi==1.8.3
futures==3.0.5
lxml==3.6.4
peewee==2.8.5
psycopg2==2.6.2
pycparser==2.14
pypi-server==0.3.30
singledispatch==3.4.0.3
six==1.10.0
slimurl==0.7.6
tornado==4.4.2
tornado-xmlrpc==1.3
```

Running server using:

```
$ pypi-server --address=0.0.0.0
```

pip configuration (~/.pip/pip.conf):

```
[global]
index-url = http://<domain here>:8080/simple
trusted-host = <domain here>
```

Installing package using:

```
$ pip install coverage
```

Logged error:

```
[E 161010 08:52:10 web:1548] Uncaught exception GET /simple/coverage/ (10.10.50.180)
    HTTPServerRequest(protocol='http', host='10.10.50.98:8080', method='GET', uri='/simple/coverage/', version='HTTP/1.1', remote_ip='10.10.50.180', headers={'Accept-Encoding': 'gzip, deflate', 'Host': '10.10.50.98:8080', 'Accept': 'text/html', 'User-Agent': 'pip/8.1.2 {"cpu":"x86_64","distro":{"id":"Twenty Two","libc":{"lib":"glibc","version":"2.2.5"},"name":"Fedora","version":"22"},"implementation":{"name":"CPython","version":"2.7.10"},"installer":{"name":"pip","version":"8.1.2"},"openssl_version":"OpenSSL 1.0.1k-fips 8 Jan 2015","python":"2.7.10","system":{"name":"Linux","release":"4.4.14-200.fc22.x86_64"}}', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=600'})
    Traceback (most recent call last):
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/pypi_server/handlers/pypi/simple/files.py", line 118, in get
        pkg = yield self.proxy_package(package)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/pypi_server/handlers/pypi/simple/files.py", line 162, in proxy_package
        pkg = yield proxy_remote_package(pkg_real_name)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/pypi_server/cache.py", line 194, in wrap_gen
        f = gen.throw(e)
      File "/home/sdomkowski/ve/pypi-server/lib/python2.7/site-packages/pypi_server/handlers/pypi/simple/files.py", line 69, in proxy_remote_package
        yield [release_fetch(pkg, release) for release in release_part]
    OperationalError: database is locked
[E 161010 08:52:10 web:1971] 500 GET /simple/coverage/ (10.10.50.180) 11279.90ms
```

**Comment by mosquito** [comment]
Try to use `postgres` instead `sqlite3` as a database engine.
