### ISSUE TITLE
ImportError: cannot import name gensalt

### ISSUE THREAD

**Issue by cgsimmons** [mosquito/pypi-server#36]
After installing pypi-server and pypi-server[postgres] I get the error when running pypi-server command:
`ImportError: cannot import name gensalt`

Stack trace:
```
Traceback (most recent call last):
  File "/home/my_home/environments/.env2/bin/pypi-server", line 7, in <module>
    from pypi_server.server import run
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/server.py", line 20, in <module>
    from pypi_server.handlers.pypi.proxy.client import PYPIClient
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/handlers/__init__.py", line 44, in <module>
    import pypi_server.handlers.pypi
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/handlers/pypi/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi import simple
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/handlers/pypi/simple/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi.simple.packages import PackagesHandler
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/handlers/pypi/simple/packages.py", line 9, in <module>
    from pypi_server.db.packages import Package, PackageVersion, PackageFile
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/db/__init__.py", line 17, in <module>
    from .migrator.model import Migrations
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/db/migrator/__init__.py", line 22, in <module>
    import pypi_server.db.migrator.migrations
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/db/migrator/migrations/__init__.py", line 32, in <module>
    sys.modules["{}.{}".format(__name__, mod.name)] = imp.load_source(mod.name, mod.path)
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/db/migrator/migrations/001_create_tables.py", line 3, in <module>
    from pypi_server.db.users import Users
  File "/home/my_home/environments/.env2/local/lib/python2.7/site-packages/pypi_server/db/users.py", line 5, in <module>
    from playhouse.fields import gensalt, hashpw
ImportError: cannot import name gensalt
```

**Comment by cgsimmons** [comment]
Works fine when running from repo clone. So latest commits haven't made it into pip.

**Comment by mosquito** [comment]
Please try to use 0.4.8 docker image or update from release files
