### ISSUE TITLE
Software crashes time to time

### ISSUE THREAD

**Issue by executoronline** [mosquito/pypi-server#42]
Hello,

sometimes the pypi-server crashes with following exception. This happens when I upload a new version of a package over setup.py. But this happens only when the server was running over some time. When I restart the cotainer it works all well again.

BR Marcus

```python
[I 190705 12:47:38 client:53] Remote PYPI index updated: 186248 packages,
[W 190705 13:21:50 httputil:774] multipart/form-data missing headers,
[I 190705 13:21:50 package:242] Calling action: file_upload,
[E 190705 13:21:50 base:36] connection already closed,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3830, in execute_sql,
        cursor.execute(sql, params or ()),
    psycopg2.OperationalError: server closed the connection unexpectedly,
    	This probably means the server terminated abnormally,
    	before or while processing the request.,
    ,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    psycopg2.InterfaceError: connection already closed,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3833, in execute_sql,
        self.rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    peewee.InterfaceError: connection already closed,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
        result = self.fn(*self.args, **self.kwargs),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/handlers/pypi/package.py", line 123, in check_password,
        user = Users.check(login, password),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/db/users.py", line 77, in check,
        user = user[0] if user else None,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3298, in __len__,
        return len(self.execute()),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3274, in execute,
        self._qr = ResultWrapper(model_class, self._execute(), query_meta),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 2939, in _execute,
        return self.database.execute_sql(sql, params, self.require_commit),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3837, in execute_sql,
        self.commit(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3833, in execute_sql,
        self.rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    peewee.InterfaceError: connection already closed,
[E 190705 13:21:50 web:1591] Uncaught exception POST /pypi (1.2.3.4),
    HTTPServerRequest(protocol='https', host='pypi.domain.com', method='POST', uri='/pypi', version='HTTP/1.1', remote_ip='1.2.3.4', headers={'Host': 'pypi.domain.com', 'User-Agent': 'Python-urllib/3.6', 'Content-Length': '25537', 'Accept-Encoding': 'identity', 'Authorization': 'Basic xxx==', 'Content-Type': 'multipart/form-data; boundary=--------------GHSKFJDLGDS7543FJKLFHRE75642756743254', 'X-Forwarded-For': '1.2.3.4', 'X-Forwarded-Host': 'pypi.domain.com', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Server': '1abaf1dbe971', 'X-Real-Ip': '1.2.3.4'}),
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3830, in execute_sql,
        cursor.execute(sql, params or ()),
    psycopg2.OperationalError: server closed the connection unexpectedly,
    	This probably means the server terminated abnormally,
    	before or while processing the request.,
    ,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    psycopg2.InterfaceError: connection already closed,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3833, in execute_sql,
        self.rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    peewee.InterfaceError: connection already closed,
    ,
    During handling of the above exception, another exception occurred:,
    ,
    Traceback (most recent call last):,
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/web.py", line 1512, in _execute,
        result = yield result,
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run,
        value = future.result(),
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result,
        raise_exc_info(self._exc_info),
      File "<string>", line 4, in raise_exc_info,
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run,
        yielded = self.gen.throw(*exc_info),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/handlers/pypi/package.py", line 243, in post,
        yield maybe_future(method()),
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run,
        value = future.result(),
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result,
        raise_exc_info(self._exc_info),
      File "<string>", line 4, in raise_exc_info,
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/gen.py", line 1063, in run,
        yielded = self.gen.throw(*exc_info),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/handlers/pypi/package.py", line 146, in wrap,
        self.current_user = yield check_password(username, password),
      File "/usr/share/python/app/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run,
        value = future.result(),
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result,
        return self.__get_result(),
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result,
        raise self._exception,
      File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
        result = self.fn(*self.args, **self.kwargs),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/handlers/pypi/package.py", line 123, in check_password,
        user = Users.check(login, password),
      File "/usr/share/python/app/lib/python3.7/site-packages/pypi_server/db/users.py", line 77, in check,
        user = user[0] if user else None,
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3298, in __len__,
        return len(self.execute()),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3274, in execute,
        self._qr = ResultWrapper(model_class, self._execute(), query_meta),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 2939, in _execute,
        return self.database.execute_sql(sql, params, self.require_commit),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3837, in execute_sql,
        self.commit(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3833, in execute_sql,
        self.rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__,
        reraise(new_type, new_type(*exc_args), traceback),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 135, in reraise,
        raise value.with_traceback(tb),
      File "/usr/share/python/app/lib/python3.7/site-packages/peewee.py", line 3849, in rollback,
        self.get_conn().rollback(),
    peewee.InterfaceError: connection already closed,
[E 190705 13:21:50 web:2064] 500 POST /pypi (1.2.3.4) 127.42ms,
/usr/share/python/app/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.,
  """),
```

**Comment by evansano** [comment]
This is likely because of idle connection garbage collection. This can be verified by starting up the server, running a few commands, and waiting more than 15 minutes (Don't let the service touch the database for that time). If after those 15 minutes of idle time you hit the error above, it is likely the garbage collection by either [docker ](https://success.docker.com/article/ipvs-connection-timeout-issue) or psycopg2. If using Postgres as a backend, you fix this by starting up postgres with tcp_keepalives_idle specified to a time under the 15 minute mark. An example in my k8s deployment is as follows:

`args: ["postgres", "-c", "tcp_keepalives_idle=300"]`
